### ISSUE TITLE
neuron-follow-thing-at-point opens zquery.md

### ISSUE THREAD

**Issue by srid** [felko/neuron-mode#13]
When point is at a zquery URI, `neuron-follow-thing-at-point` opens a new buffer named `zquery.md` (it could be `search.md` or `tag.md` depending on where exactly the point is in the URI). It should instead do perhaps one of the following:

- Do nothing
- Bring up the query results, behaving like `neuron-edit-zettel` but filtered to zettels matching the query

I somehow recall that it used to behave like the later?

**Comment by felko** [comment]
Thanks, this should be fixed by <https://github.com/felko/neuron-mode/commit/0b0c24f3ef9bee2d26783093ac832e785e708c8b>
