### ISSUE TITLE
Selecting zettel with point at a tags query shows nil

### ISSUE THREAD

**Issue by srid** [felko/neuron-mode#14]
![image](https://user-images.githubusercontent.com/3998/80291142-f48bf800-8718-11ea-8e48-d3e49fafec1a.png)

To reproduce:
- put the point at `[.](zquery://tags?filter=**)`
- `SPC m o`

**Comment by srid** [comment]
I wonder if `neuron query`'s JSON structure should be changed to indicate the type of the query.

**Comment by felko** [comment]
> I wonder if neuron query's JSON structure should be changed to indicate the type of the query.

I don't think so, I can just parse the URI and extract whether it was a search or a tags query.

**Comment by felko** [comment]
Should be solved in <https://github.com/felko/neuron-mode/commit/5961760404c2c62db262ef29581e2938801ae718>
