### ISSUE TITLE
Should `SPC z e` work like `SPC p f`? (projectile)

### ISSUE THREAD

**Issue by srid** [felko/neuron-mode#15]
`SPC p f` is `projectile-find-file`. Projectile is a project management systems for Emacs. `SPC p p` works like `SPC z s` (select zettelkasten), but it also prompts to open the first file.

`SPC p f`, which allows you to open a file in the current project, however, is slightly different ... in that, if your current active buffer is from _some other_ project, then it will show a list of files in *that* project (regardless which project you had choosen before).

I work with multiple zettelkastens. I select the Foo zettelkasten; and later I would be editing the Bar zettelkasten. And when I do `SPC z e` here, neuron-mode would show me a list of zettels from Foo, when I would have expected it to show me the list from Bar.

This behaviour also affects `neuron-follow-thing-at-point` (which pulls zettels from another zettelkasten, despite using the query from a different one).

**Comment by felko** [comment]
Good idea. I already changed `neuron-select-zettel` to search only by title, whereas before it used `counsel-rg` to search by content (with `title: ` as a default prefix). I now use `SPC s p` to search my zettelkasten by content. I think neuron-mode could benefit from relying explicitly on projectile to take care of figuring out what zettelkasten is currently being worked on, searching, and selecting zettelkastens (see #10).

**Comment by felko** [comment]
Thanks to <https://github.com/felko/neuron-mode/commit/60be5c1740385a2b1cb92c83931494667fb1da3c>, `SPC z e` now selects zettels from the current working directory which can be set by projectile.
