### ISSUE TITLE
`SPC z z` - prompt title

### ISSUE THREAD

**Issue by srid** [felko/neuron-mode#17]
Would be nice if this prompted for the title of the new zettel. A few times I'd create new zettels by mistake, only having to delete them manually in the command line.

**Comment by felko** [comment]
I can make a M-x customize option to control this behavior.

(protip: SPC f D deletes the current file)

**Comment by felko** [comment]
With the new title overlay feature, prompting for the title makes a lot more sense since it avoids regenerating the cache after using `neuron-insert-new-zettel`.

**Comment by srid** [comment]
Perhaps the prompt can use a default title, so that the user can simply hit "enter" without having to fill in the title? 

`M-x replace-string` when used the second time does that in doom-emacs (don't know how exactly though):

![image](https://user-images.githubusercontent.com/3998/80726836-f0722880-8ad2-11ea-9e1c-7af2a5c891d3.png)

**Comment by felko** [comment]
Good idea, I don't think behaving exactly like replace-string makes sense because it takes the last input, but I can just take "Untitled" as the default value when the title is a blank string.
