### ISSUE TITLE
Screenshots and asciicasts

### ISSUE THREAD

**Issue by srid** [felko/neuron-mode#24]
Would be nice to have in the README, to visualy demonstrate the neuron-mode features at first glance.

Here's one to begin with:

![image](https://user-images.githubusercontent.com/3998/80873287-6fa75e00-8c85-11ea-9cf7-6e03db001d00.png)

(Or/and we can add them to neuron.zettel.page as a zettel).

**Comment by felko** [comment]
I think I can close this thanks to your asciicast PR
