### ISSUE TITLE
Daily notes

### ISSUE THREAD

**Issue by srid** [felko/neuron-mode#28]
This would be a cool feature, similar to roam. `M-x neuron-open-daily-notes`.

* Open `%Y-%m-%d.md` if it already exists
* Otherwise create it and open.

Might want a customize field for using a predefined tag (I use `journal/daily` on my daily notes, so they can be queried from another zettel).

**Comment by felko** [comment]
I think we can close this for now, although additional features for daily notes are welcome (see <https://github.com/felko/neuron-mode/pull/31#issuecomment-638500851> for ideas).
