### ISSUE TITLE
Navigate "nearby zettels"

### ISSUE THREAD

**Issue by srid** [felko/neuron-mode#30]
Would be nice to have a command to open a zettel by backlink (folgezettel or not) relationship.

https://github.com/srid/neuron/pull/206 can be used today, however a `QueryGraph_BacklinksOf` would probably be easier (to shift the processing from emacs to neuron).

**Comment by pjones** [comment]
@srid Is there an open issue for `neuron` to implement `QueryGraph_BacklinksOf`?

Trying to build a backlink display from the graph JSON in elisp would be a bit laborious.  I'd much rather do it in Haskell.

**Comment by srid** [comment]
There is no issue for it, but PR is welcome. 

Basically add a constructor [here](https://github.com/srid/neuron/blob/ac46252e0d68a1d7176c223515b04a56f9e5cfa9/neuron/src/lib/Neuron/Zettelkasten/Query/Graph.hs#L21-L23), add to CLI spec [here](https://github.com/srid/neuron/blob/ac46252e0d68a1d7176c223515b04a56f9e5cfa9/neuron/src/app/Neuron/CLI/Types.hs#L127-L138) and finally add the implementation in [`runGraphQuery`](https://github.com/srid/neuron/blob/ac46252e0d68a1d7176c223515b04a56f9e5cfa9/neuron/src/lib/Neuron/Zettelkasten/Query.hs#L45-L47).

**Comment by clemera** [comment]
Is it indicated in the completion UI if the the backlinks are folgezettel or not? I'm interested in tying neuron, I think it looks very interesting but it looks like the backlinks/uplinks listings are only available for the web UI? Would it be possible to have that indication of backlinks/uplinks directly in the markdown buffer like in the WebUI?
