### ISSUE TITLE
Fallback on generated HTML when rib is not running

### ISSUE THREAD

**Issue by felko** [felko/neuron-mode#4]
Currently `neuron-rib-open-page` opens a new tab in the browser on `localhost`, regardless of whether a rib instance is running.

It could be useful to replace it with a `neuron-open-zettel` function that would open the generated HTML page instead when no instance is running.

**Comment by felko** [comment]
The `neuron open` command from <https://github.com/srid/neuron/pull/79> allows this to be implemented straightforwardly.

**Comment by srid** [comment]
Currently I'm using it with this change:
![image](https://user-images.githubusercontent.com/3998/79264499-ac402080-7e62-11ea-8217-245eae7ae0c9.png)

**Comment by felko** [comment]
Yeah as you mentioned earlier, there is no reason to use rib serve when editing zettels, since the site is purely static.
I should just implement a `neuron-rib-watch` command instead of having to serve the web application every time.

**Comment by srid** [comment]
Another option is to _automatically_ run `neuron-rib-generate` every time a zettel is created or modified (obviates the need for `neuron rib -w`, which has to be a long-running process).

**Comment by felko** [comment]
I could do this yeah, generating every time a zettel is created or modified seems a bit too much though. Maybe we could generate when `neuron-open-current-zettel` is called instead.

What's the issue with long running processes?

**Comment by srid** [comment]
> I could do this yeah, generating every time a zettel is created or modified seems a bit too much though.

FWIW, `neuron rib` will run quick, and generate only modified files. `rib -w` on the other hand will begin with a full generation, and then monitor. Anyway, this can be done in user config, especially as a function like `neuron-rib-generate` now exists. 

> What's the issue with long running processes?

More moving parts. If I work with multiple zettelkastens, will there be multiple long running processes? Or would I have to stop one and start another? One-off generation is simple enough for me. So it is mostly a personal preference. I use `rib -w` only in CLI, and that too for brief periods.

EDIT: Oh, and the other benefit is that with one-off generation if there is any error I'd see it right away. This is not the case with long-running process (unless you use something like flycheck I guess, or keep the `*rib*` buffer visible).

**Comment by felko** [comment]
I guess this can be closed, I wanted to fallback rather than just open the local HTML but after using neuron-mode a little bit I noticed that I didn't used rib features at all (except watch sometimes). I'll keep the rib related functions but I'll probably remove default bindings to them in the suggested doom config.

[Your doom config](https://github.com/srid/.doom.d/blob/master/modules/tools/neuron/config.el) makes more sense.
