### ISSUE TITLE
Feature request: allow specifying host/port to listen on for rib server

### ISSUE THREAD

**Issue by bcclaywell** [felko/neuron-mode#45]
According to the neuron docs, you can specify an optional host/port to listen on as an alternative to 127.0.0.1:8080.

```
You can override server settings such as the host and port. For example,

  neuron rib -ws 127.0.0.1:8081
```

 Since many things try to use 8080 it would be nice if an alternative could be specified through a config variable or argument to `neuron-rib-serve`.

Thank you so much for neuron-mode!

**Comment by felko** [comment]
Thanks for the request, can you give it a try in <https://github.com/felko/neuron-mode/commit/43dfd9e21ee4aaf904f92965c93ad1075af1b4c7> ?

I'd like to allow these settings to be passed as arguments to `neuron-rib-serve` ultimately, which would allow multiple zettelkasens can be served simultaneously, but the rib commands need to be refactored anyway so I'll implement this later. I hope this suits your needs in the meantime

**Comment by bcclaywell** [comment]
That works perfectly, thanks so much!
