### ISSUE TITLE
The function `neuron-toggle-connection-type` fails

### ISSUE THREAD

**Issue by prsteele** [felko/neuron-mode#53]
Calling the function `neuron-toggle-connection-type` on any Zettel link emits the error

```
Symbol’s function definition is void: map-put!
```

Luckily the resolution seems straightforward, and I've made a [PR](https://github.com/felko/neuron-mode/pull/52) to fix this.

I'm using Emacs 26.3, and the issue persisted when launching with `emacs -Q` and manually `eval-buffer`ing `neuron-mode.el`, `s.el`, `dash.el`, `f.el`, and `markdown-mode.el`.

**Comment by felko** [comment]
Fixed in <https://github.com/felko/neuron-mode/commit/ea260a0f8f2bb4b15c9a9cba6be5f16865d05160>
