### ISSUE TITLE
Cannot bind neuron-toggle-connection-type

### ISSUE THREAD

**Issue by bulbousBullfrog** [felko/neuron-mode#59]
I would like to locally bind this function to a key. I've tried two methods

1. with use-package and :bind  
2. interactively with M-x local-set-key

but get the following error

`neuron-toggle-connection-type: Symbol’s function definition is void: map-put!`

This seems possibly related to the #53 . The implemented change in ea260a0 enabled me to use the function interactively, but I am unable to bind it. 
Would it be possible to change the implementation so that it can be bound?

**Comment by felko** [comment]
I don't understand how one can call a function interactively yet cannot bind it to a key. Does it show some kind of error message when trying to bind the key, after you updated neuron-mode?

**Comment by bulbousBullfrog** [comment]
It seems to perhaps be a problem with use-package. Trying the above M-x local-set-key does seem to work after all, so I am guessing that the way use-package binds local keys doesn't play well with something. I will close it here, and maybe look for help in their repo.
