### ISSUE TITLE
Support wiki links

### ISSUE THREAD

**Issue by srid** [felko/neuron-mode#60]
Syntax is documented here: https://neuron.zettel.page/2011504.html

Basically `<...>` is deprecated (still supported) in favour of the new default: `[[...]]` as well as `[[[...]]]`.

**Comment by srid** [comment]
``[[Some note, with puctuation]]`` is now a valid link in neuron.

cf.

- https://neuron.zettel.page/id.html
- https://github.com/srid/neuron/issues/399

**Comment by vizziv** [comment]
I'm totally new to elisp, but I'm willing to have a go at this. Can anyone give me a few pointers to places in the code that would need to change?

**Comment by srid** [comment]
@vizziv Probably `neuron-link-regex`: https://github.com/felko/neuron-mode/blob/6042cb8960f0018d19db7be84e76622bdfaed5ec/neuron-mode.el#L796-L799

**Comment by TheKK** [comment]
Hi @vizziv, are you working on this? If not then I'd like to help as well :)

**Comment by vizziv** [comment]
By all means, go ahead! (I never managed to get started on this.)

**Comment by sudeepdino008** [comment]
WIP here - https://github.com/sudeepdino008/neuron-mode/commit/6455f03a4c30fd33e273ce07266f94dff856add3.
It supports folgezettel and ordinary links ( ids containing spaces might not work yet).  
It still needs to support tag wikilinks (see tag trees [here](https://neuron.zettel.page/tags.html)).

EDIT:

pull request here: https://github.com/felko/neuron-mode/pull/67  
Company mode is still not supported. I'd appreciate some help there as I don't use company mode.

**Comment by felko** [comment]
Closing since #67 was merged
