### ISSUE TITLE
Another failure when initializing neuron mode

### ISSUE THREAD

**Issue by jcborras** [felko/neuron-mode#61]
Maybe related to #58 but these symptoms are different.

My setup: Emacs v26.3, neuron v0.6.10.0, neuron-mode 20200806.833 (installed via melpa).
Zettelkasten exists in `~/.zettlekasten` as the default variable for the location states.
`M-x neuron-mode` loads the mode actually but the `*Messages*` buffer contains the following:

```
user-error: Command "neuron --zettelkasten-dir /home/MYSELF/zettelkasten query --uri z\:zettels" exited with code 1: Invalid option `--zettelkasten-dir'

Usage: neuron [--version] [-d PATH] COMMAND
  Neuron, future-proof Zettelkasten app <https://neuron.zettel.page/>
```
It seem as if `neuron-mode` is passing the `--zettelkasten-dir` option to the `neuron` application but that option is unrecognized by it. Strangely enough that line has been in `(defun neuron--make-command ...)` for months without giving any pain. What am I missing?

Needless to say both `C-c C-z` for `neuron-new-zettel` and `C-c C-e` for `neuron-edit-zettle` produce the same error.

Also sad to see `M-x neuron-select-zettelkasten` gone which comes handy for people having zettelkastens on different subjects like quantum mechanics and bean growing.

**Comment by felko** [comment]
That is most likely due to the recent CLI update in neuron: <https://github.com/srid/neuron/issues/389>.
I don't have much time to update neuron-mode these days but this should be easily fixable.

> Also sad to see M-x neuron-select-zettelkasten gone which comes handy for people having zettelkastens on different subjects like quantum mechanics and bean growing.

I use projectile by treating zettelkastens as projects, which is better in my opinion since I can benefit from features like selecting recent zettelkastens.

**Comment by jcborras** [comment]
So in theory would changing `--zettelkasten-dir` for `--zettelkasten-directory` in the `neuron--make-command` function do the trick?

**Comment by srid** [comment]
Use `-d`
