### ISSUE TITLE
'neuron-add-tag' is unable to identify tags with latest version of neuron

### ISSUE THREAD

**Issue by ednolan** [felko/neuron-mode#69]
'neuron-add-tag' doesn't seem to be working with the latest version of neuron. When I use neuron version 1.1.8.0 (commit 9dc3bbd), the function is able to find all my tags, but with neuron version 1.9.1.3 (commit 22dad5f), the set of tags that the function prompts me with is empty.

**Comment by srid** [comment]
This might be a regression in neuron. `neuron query -u z:tags` now spits out `unTagNode`, which might be wrong. 

If so, it should be fixed in neuron.

**Comment by srid** [comment]
Done.

**Comment by ednolan** [comment]
That looks to have resolved the issue. Thanks!
