### ISSUE TITLE
neuron v2 query

### ISSUE THREAD

**Issue by srid** [felko/neuron-mode#73]
After the plugin architectural refactor in neuron v2, the query interface has radically changed.
 
I've just added `neuron query --zettels` and `neuron query --tags` that should be helpful for editor support. You might want to make neuron-mode.el use that. /cc @azazel75

Change: https://github.com/srid/neuron/pull/547

Docs: https://neuron.zettel.page/query.html (do a full browser refresh if you see the old docs)

**Comment by felko** [comment]
Should work in <https://github.com/felko/neuron-mode/commit/f2560690b68d5c0cd65c49802c5c86bf17944b6a>, but I removed the feature that displayed the number of zettels associated with each tag when showing prompts for selecting tags, for now.
I had to work with the internal representation of plugin data though, so it might break later if the PluginData field changes format.

**Comment by srid** [comment]
What are you using `PluginData` (which is really internal data for plugins) for? Shouldn't `neuron query --tags` and `neuron query --tag=foo` be sufficient?

**Comment by felko** [comment]
I need `PluginData` for the `Tags` plugin when I display the list of tags next to each zettel
![image](https://user-images.githubusercontent.com/9366592/106386540-bfae7f00-63d5-11eb-93f4-f9e80db660c0.png).
