### ISSUE TITLE
Release (or tag) for the last version that worked with Neuron 1.0

### ISSUE THREAD

**Issue by pjones** [felko/neuron-mode#76]
It appears that this package is using features from Neuron which haven't been released yet.

NixOS 21.05 includes Neuron 1.0 but also the latest melpa release of this package.  Starting Emacs  in this environment and using `neuron-edit-zettel` tries to call Neuron with `query --zettels` which fails since the new query interface is a feature of the unreleased version of Neuron.

It would be nice if there was an official release of this package that supported Neuron 1.0.  I'm using revision `ae89eaaec0da938e748adda3a8412b79cd333d67` which seems to work but might be a little older than necessary.

**Comment by felko** [comment]
Done: <https://github.com/felko/neuron-mode/releases/tag/v1.0>
Thanks for reporting
